spring:
  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${application.spring.datasource.url}
    username: ${application.spring.datasource.username}
    password: ${application.spring.datasource.password}

  jpa:
    database: mysql
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
        use_sql_comments: true
        jdbc:
          batch_size: 20
          fetch_size: 50

    defer-datasource-initialization: true

jwt:
  secret: ${application.jwt.secret}
  refresh-token-expiration-seconds: 90

logging:
  level:
    root: info
    org:
      hibernate: debug
      springframework:
        orm: trace
        jdbc: trace
